import Head from "next/head";
import Image from "next/image";

export default function Home() {
    return (
        <div>
            <Head>
                <title>MyEvent App</title>
                <meta name="description" content="Generated by MyEvent App" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1>Hello World!</h1>
            </main>
        </div>
    );
}
